# Generated by Django 2.0 on 2017-12-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_edited', models.DateTimeField(auto_now=True, verbose_name='Date-time of modification')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('resume', models.TextField()),
            ],
            options={
                'ordering': ['date_time_edited'],
            },
        ),
    ]
