# Generated by Django 2.0 on 2017-12-27 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20171226_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumelog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
