# Generated by Django 2.0 on 2017-12-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20171226_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
