# Generated by Django 2.0 on 2017-12-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20171226_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date-time of creation')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='resumelog',
            options={'ordering': ['-date_time_edited']},
        ),
        migrations.AlterField(
            model_name='resumelog',
            name='date_time_edited',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date-time of modification'),
        ),
        migrations.AlterField(
            model_name='resumelog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
