# Generated by Django 2.0.1 on 2018-01-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactdata_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='answer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactData'),
        ),
    ]
