# Generated by Django 2.0 on 2017-12-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visits',
            field=models.BigIntegerField(default=0),
        ),
    ]
