# Generated by Django 2.0 on 2017-12-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171230_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time_published',
            field=models.DateField(verbose_name='Date of publication'),
        ),
    ]
