# Generated by Django 2.0 on 2017-12-31 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171230_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_published', '-date_time_modification']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_time_published',
            new_name='date_published',
        ),
    ]
