# Generated by Django 2.0 on 2018-01-03 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171230_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_time_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 17, 16, 58, 770092), verbose_name='Published Date-Time'),
        ),
    ]
