# Generated by Django 2.0 on 2018-01-03 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_date_time_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['visible', '-date_time_published', '-date_time_modification']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_time_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 17, 18, 26, 64355), verbose_name='Published Date-Time'),
        ),
    ]
