# Generated by Django 2.0 on 2018-01-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180103_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Published Date'),
        ),
    ]
