# Generated by Django 2.0 on 2018-01-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180106_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(),
        ),
    ]
