# Generated by Django 2.0 on 2018-01-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180106_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['visible', '-date_time_created', '-date_time_modification']},
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='project_logos/'),
        ),
    ]
